# Generated by Django 3.2.3 on 2021-06-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('correo', models.CharField(max_length=20, verbose_name='Correo Electronico')),
                ('usuario', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Usuario')),
                ('contraseña', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('fchnac', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
        ),
    ]
